// <auto-generated />
namespace Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class eventUserRelation31 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(eventUserRelation31));
        
        string IMigrationMetadata.Id
        {
            get { return "201607011258404_eventUserRelation31"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
